name: postman api tests

on: 
  push:
    branches:
      - main

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: docker-compose up -d
      - uses: matt-ball/newman-action@master
        with:
          collection: ./tests/newman/aboutyou.postman_collection.json
          environment: ./tests/newman/aboutyou.postman_environment.json